# Generated by Django 5.0.1 on 2025-06-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("MEMBERS", "Members List"),
                            ("CHECKINS", "Check-in History"),
                            ("REVENUE", "Revenue Report"),
                            ("SUBSCRIPTIONS", "Subscriptions Report"),
                            ("EXPIRING_MEMBERSHIPS", "Expiring Memberships"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        default="MEMBERS",
                        max_length=50,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EXCEL", "Excel"), ("CSV", "CSV")],
                        default="PDF",
                        max_length=10,
                        verbose_name="Export Format",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Report Parameters"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="File Path"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
        ),
    ]
