# Generated by Django 5.0.1 on 2025-06-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
